name: telegram-bot
services:
  - name: telegram-bot
    type: worker
    image: python:3.10
    env:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    build:
      commands:
        - pip install -r requirements.txt
    run:
      command: python bot.py
